spring:
  application:
    name: producer

  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PWD:pwd}
      database: ${REDIS_DB:0}